### ISSUE TITLE
Problem installing ImageMagick (Caption and meme commands are not working)

### ISSUE THREAD

**Issue by cattydev** [ExillustX/GifMemeGen#11]
hey man the caption and meme commands are giving me errors. 
that is meme command's error in terminal
> Error: Failed to call 'convert ( "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\input.jpg" -coalesce -resize 420x553 ) -stroke black -fill white -font "./impact.ttf" ( -strokewidth 2.76 -pointsize 69 -annotate +0+10 "EXAMPLE TOP" -gravity south ) ( -strokewidth 2.76 -pointsize 69 -annotate +0+6.55 "EXAMPLE BOT" -gravity north ) "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\unoptimized-output.jpg"', which was mapped to '"C:\Windows\System32\convert.exe" ( "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\input.jpg" -coalesce -resize 420x553 ) -stroke black -fill white -font "./impact.ttf" ( -strokewidth 2.76 -pointsize 69 -annotate +0+10 "EXAMPLE TOP" -gravity south ) ( -strokewidth 2.76 -pointsize 69 -annotate +0+6.55 "EXAMPLE BOT" -gravity north ) "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\unoptimized-output.jpg"'. Error is 'Command failed: "C:\Windows\System32\convert.exe" ( "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\input.jpg" -coalesce -resize 420x553 ) -stroke black -fill white -font "./impact.ttf" ( -strokewidth 2.76 -pointsize 69 -annotate +0+10 "EXAMPLE TOP" -gravity south ) ( -strokewidth 2.76 -pointsize 69 -annotate +0+6.55 "EXAMPLE BOT" -gravity north ) "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\unoptimized-output.jpg"
Invalid Parameter - "C:\Users\DELL\tmp\15e53db5-a333-46ff-a515-36745bf8cf62\input.jpg"
'.
    at c:\Users\DELL\Desktop\aaaaaa\node_modules\imagemagick-cli\src\exec.js:49:27
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  stdout: '',
  stderr: 'Invalid Parameter - "C:\\Users\\DELL\\tmp\\15e53db5-a333-46ff-a515-36745bf8cf62\\input.jpg"\r\n'
}

and caption's error is 
> Error: Failed to call 'convert -background white -interline-spacing 0 -kerning 0 -fill black  -font "./caption-font.otf" -pointsize 34 -size 370x -gravity Center  caption:"example" PNG24:C:\Users\DELL\tmp\4b188c92-5b7a-4b11-9b09-6a2101e157d5\caption.png', which was mapped to '"C:\Windows\System32\convert.exe" -background white -interline-spacing 0 -kerning 0 -fill black  -font "./caption-font.otf" -pointsize 34 -size 370x -gravity Center  caption:"example" PNG24:C:\Users\DELL\tmp\4b188c92-5b7a-4b11-9b09-6a2101e157d5\caption.png'. Error is 'Command failed: "C:\Windows\System32\convert.exe" -background white -interline-spacing 0 -kerning 0 -fill black  -font "./caption-font.otf" -pointsize 34 -size 370x -gravity Center  caption:"example" PNG24:C:\Users\DELL\tmp\4b188c92-5b7a-4b11-9b09-6a2101e157d5\caption.png
Invalid Parameter - white
'.
    at c:\Users\DELL\Desktop\aaaaaa\node_modules\imagemagick-cli\src\exec.js:49:27
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  stdout: '',
  stderr: 'Invalid Parameter - white\r\n'
}

how can i fix those?

**Comment by exil0867** [comment]
Do you have ImageMagick installed?
If not please install it and make sure you check "Add application directory to your system path" and "Install legacy utilities".

**Comment by Wolfkid200444** [comment]
After installing ImageMagick what do i do?

**Comment by Wolfkid200444** [comment]
After installing ImageMagick is still giving me this errors

**Comment by exil0867** [comment]
> After installing ImageMagick is still giving me this errors
> 

Open a terminal and type `convert -version.` to verify if it was properly installed.

**Comment by cattydev** [comment]
> > After installing ImageMagick is still giving me this errors
> 
> Open a terminal and type `convert -version.` to verify if it was properly installed.

I downloaded from imagemagick.org, still giving same error.

I ran `convert -version.` and output is:
https://pastebin.pl/view/9d960a55

**Comment by cattydev** [comment]
Hey! Commands are working, thanks so much but how can i run this repository on github?

**Comment by exil0867** [comment]
You'll need to deploy the bot on a server, try Heroku since it's user-friendly.

**Comment by cattydev** [comment]
> You'll need to deploy the bot on a server, try Heroku since it's user-friendly.

i have a repository on github and heroku running this. How do i upload Imagemagick?

**Comment by exil0867** [comment]
If i recall correctly there are a few ImageMagick buildbpacks for Heroku, try them.

**Comment by cattydev** [comment]
giving another error -.- 

> index.js:58
  if (commandCooldown[label].has(userId)) return message.channel.send(`This command has a cooldown of ${commandsMap.get(label).help.cooldown} seconds. Please wait a bit and try again!`).then(msg => msg.delete({ timeout: 6000 }));
                             ^
TypeError: Cannot read property 'has' of undefined
    at Client.<anonymous> (C:\Users\DELL\Desktop\aaaaaa\index.js:58:30)
    at Client.emit (events.js:310:20)
    at MessageCreateAction.handle (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\ws\lib\websocket.js:797:20)

**Comment by Wolfkid200444** [comment]
it seems [label] is undefined try `console.logging` commandCooldown to see what u get

**Comment by cattydev** [comment]
> it seems [label] is undefined try `console.logging` commandCooldown to see what u get

on index.js:53
> let label = split[0];

**Comment by Wolfkid200444** [comment]
> Hey! Commands are working, thanks so much but how can i run this repository on github?

Btw how u made it run?

**Comment by Wolfkid200444** [comment]
because for me the commands are running but nothing is been placed on the images

**Comment by Wolfkid200444** [comment]
wait it seems it started running

**Comment by cattydev** [comment]
> wait it seems it started running

started but i got an error on index.js when i use meme command. caption is working.
> \index.js:58
  if (commandCooldown[label].has(userId)) return message.channel.send(`This command has a cooldown of ${commandsMap.get(label).help.cooldown} seconds. Please wait a bit and try again!`).then(msg => msg.delete({ timeout: 6000 }));
                             ^
TypeError: Cannot read property 'has' of undefined
    at Client.<anonymous> (C:\Users\DELL\Desktop\aaaaaa\index.js:58:30)
    at Client.emit (events.js:310:20)
    at MessageCreateAction.handle (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (C:\Users\DELL\Desktop\aaaaaa\node_modules\ws\lib\websocket.js:797:20)

**Comment by exil0867** [comment]
It throwed an error because for some reason the ID of the user was undefined, i've never had this issue though.
Well it's only a part of the cooldown functionality so you could just disable cooldowns.

**Comment by cattydev** [comment]
> It throwed an error because for some reason the ID of the user was undefined, i've never had this issue though.
> Well it's only a part of the cooldown functionality so you could just disable cooldowns.

thanks :/ i will try to remove cooldown

**Comment by Wolfkid200444** [comment]
How do install ImageMagick on a Headless Ubuntu vps wh3uehdvj3o idk??

**Comment by realProgamerX2** [comment]
how do i actually apply the image magic to the heroku thing (already set up)

**Comment by realProgamerX2** [comment]
i got heroku set up, bot running and online in my server just the commands dont work
